{
	"_Type": "Action.Type.OfflineOData.Close",
	"ActionResult": {
		"_Name": "close"
	},
	"OnFailure": "/COE_Dashboard/Actions/Service/CloseOfflineFailureMessage.action",
	"OnSuccess": "/COE_Dashboard/Actions/Service/CloseOfflineSuccessMessage.action",
	"Service": "/CoE_Dashboard/Services/service1.service",
	"Force": true
}