{
	"_Type": "Action.Type.ProgressBanner",
	"OnFailure": "/COE_Dashboard/Actions/Service/SyncFailureMessage.action",
	"OnSuccess": "/COE_Dashboard/Actions/Service/UploadOffline.action",
	"Message": "Upload in progress...",
	"CompletionMessage": "Sync completed",
	"CompletionTimeout": 7
}