{
    "ParentLink": {
        "Property": "skills",
        "Target": {
            "EntitySet": "Employees",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/CoE_Dashboard/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/CoE_Dashboard/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "ID": "#Control:ID/#Value",
        "SUBID": "#Control:SUBID/#Value",
        "Name": "#Control:Name/#Value",
        "Description": "#Control:Description/#Value",
        "Level": "#Control:Level/#Value",
        "module_ID": "#Control:module_ID/#SelectedValue",
        "employee_ID": "#Control:employee_ID/#SelectedValue"
    },
    "Target": {
        "EntitySet": "Skills",
        "Service": "/CoE_Dashboard/Services/service1.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}