{
    "CreateLinks": [],
    "OnFailure": "/CoE_Dashboard/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/CoE_Dashboard/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "ID": "#Control:ID/#Value",
        "Name": "#Control:Name/#Value",
        "Description": "#Control:Description/#Value",
        "module_ID": "#Control:module_ID/#SelectedValue"
    },
    "Target": {
        "EntitySet": "Projects",
        "Service": "/CoE_Dashboard/Services/service1.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}